### ISSUE TITLE
Freezes upon rendering a frame (e.g. when animated GIFs are used)

### ISSUE THREAD

**Issue by dtugend** [advancedfx/afx-cefhud-interop#10]

**Comment by dtugend** [comment]
It seems thie GIF freezing only happens when (verbose) logging is enabled, removing ` "--v=1"` seems to work around it.

**Comment by dtugend** [comment]
https://github.com/advancedfx/afx-cefhud-interop#freezes-when-logging-is-enabled

**Comment by kubo6472** [comment]
Still occurs as of today :(

**Comment by dtugend** [comment]
The default example of the latest version includes a gif, I can not reproduce the issue.

Maybe your code is not fully updated or faulty, check for errors when launchign from cmd.exe / enable logging as described here: https://github.com/advancedfx/afx-cefhud-interop/blob/main/afx-cefhud-interop/assets/examples/default/index.html#L10 and check if there's script errors from your end.

@osztenkurden did you run into nay issues with the latest v7 version regarding this?

Edit: Latest version is from 5 days ago
https://github.com/advancedfx/afx-cefhud-interop/releases/tag/v7.0.0.14-69c583d

**Comment by osztenkurden** [comment]
No, i did not. @kubo6472 if you use it with LHM, use latest afx-cefhud-interop, latest HLAE, and don't replace any dlls as it was in the older version of AR implementation. Also use LHM 3.6.2

**Comment by kubo6472** [comment]
> No, i did not. @kubo6472 if you use it with LHM, use latest afx-cefhud-interop, latest HLAE, and don't replace any dlls as it was in the older version of AR implementation. Also use LHM 3.6.2

![image](https://user-images.githubusercontent.com/26146502/154109100-35196a82-f85b-49af-9162-1c492b32688e.png)
![image](https://user-images.githubusercontent.com/26146502/154109189-f5ff4028-6dc8-45d2-9b41-85dfb52816d3.png)
I followed the instructions and got myself the latest release.7z exactly the one latest was linking to. LHM 3.6.2 and no DLLs replaced. Checked the folder permissions and everything, nope, the moment I load [gif](https://github.com/BluenationStudio/LHM-HUDs/blob/0d8a02f879636e86d5b722e74245d22099d38a1e/src/HUD/MatchBar/matchbar.scss#L305) it freezes up everything.

**Comment by dtugend** [comment]
The problem (script error) happens when resizing the window takes longer (more frames) than expected.
This should only happen if the gif already plays before connecting the first time.
A 1-line workaround / fix for this will be released in a few minutes.

**Comment by dtugend** [comment]
The problem is more severe than I thought, meaning causing intermediate frames. Will need more time.

**Comment by kubo6472** [comment]
Oh, alright. Thank you for looking into this, since this repo has 
"development paused".

**Comment by dtugend** [comment]
v7.0.0.17-4dcfd4d should fix it once and for all hopefully - if not, then I dunno /tablefip? However @osztenkurden will probably need to adjust LHM for it, since assets changed notably.

**Comment by kubo6472** [comment]
Thank you very much

**Comment by kubo6472** [comment]
![image](https://user-images.githubusercontent.com/26146502/159559983-ff319362-03dd-4f2e-949b-f5dbb8746253.png)
It works!
