### ISSUE TITLE
[HELP] Getting errors while trying to build via cmake

### ISSUE THREAD

**Issue by ItayKisous** [advancedfx/afx-cefhud-interop#8]
I've never used cmake before and I tried multiple times to install the interop. 
Tried reinstalling all the files and restarting everything.

I get the following errors:
`
 Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.19042.
CMake Warning (dev) at CMakeLists.txt:58 (find_package):
  Policy CMP0074 is not set: find_package uses <PackageName>_ROOT variables.
  Run "cmake --help-policy CMP0074" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  CMake variable CEF_ROOT is set to:

    C:/Users/Itay/Desktop/HUDS/AFX/cef-project/third_party/cef/cef_binary_87.1.12+g03f9336+chromium-87.0.4280.88_windows64

  For compatibility, CMake is ignoring the variable.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning at third_party/cef/cef_binary_87.1.12+g03f9336+chromium-87.0.4280.88_windows64/cmake/cef_variables.cmake:531 (message):
  ATL is not supported by your VC installation.
Call Stack (most recent call first):
  third_party/cef/cef_binary_87.1.12+g03f9336+chromium-87.0.4280.88_windows64/cmake/FindCEF.cmake:38 (include)
  CMakeLists.txt:58 (find_package)

-- Using Python: C:/Users/Itay/AppData/Local/Programs/Python/Python39/python.exe
-- Downloading clang-format from Google Storage...
Failed to fetch file gs://chromium-clang-format/b5f5d8d5f8a8fcd2edb5b6cae37c0dc3e129c945 for tools/buildtools/win/clang-format.exe. [Err: C:\Users\Itay\Desktop\HUDS\AFX\cef-project\tools\buildtools\external_bin\gsutil\gsutil_4.46\gsutil\gslib\vendored\boto\boto\pyami\config.py:69: UserWarning: Unable to load AWS_CREDENTIAL_FILE ()
  warnings.warn('Unable to load AWS_CREDENTIAL_FILE (%s)' % full_path)
Traceback (most recent call last):
  File "C:\Users\Itay\Desktop\HUDS\AFX\cef-project\tools\buildtools\external_bin\gsutil\gsutil_4.46\gsutil\gsutil", line 21, in <module>
    gsutil.RunMain()
  File "C:\Users\Itay\Desktop\HUDS\AFX\cef-project\tools\buildtools\external_bin\gsutil\gsutil_4.46\gsutil\gsutil.py", line 123, in RunMain
    import gslib.__main__
  File "C:\Users\Itay\Desktop\HUDS\AFX\cef-project\tools\buildtools\external_bin\gsutil\gsutil_4.46\gsutil\gslib\__main__.py", line 75, in <module>
    from gslib.command_runner import CommandRunner
  File "C:\Users\Itay\Desktop\HUDS\AFX\cef-p0> Failed to fetch file gs://chromium-clang-format/b5f5d8d5f8a8fcd2edb5b6cae37c0dc3e129c945 for tools/buildtools/win/clang-format.exe, skipping. [Err: C:\Users\Itay\Desktop\HUDS\AFX\cef-project\tools\buildtools\external_bin\gsutil\gsutil_4.46\gsutil\gslib\vendored\boto\boto\pyami\config.py:69: UserWarning: Unable to load AWS_CREDENTIAL_FILE ()
  warnings.warn('Unable to load AWS_CREDENTIAL_FILE (%s)' % full_path)
Traceback (most recent call last):
  File "C:\Users\Itay\Desktop\HUDS\AFX\cef-project\tools\buildtools\external_bin\gsutil\gsutil_4.46\gsutil\gsutil", line 21, in <module>
    gsutil.RunMain()
  File "C:\Users\Itay\Desktop\HUDS\AFX\cef-project\tools\buildtools\external_bin\gsutil\gsutil_4.46\gsutil\gsutil.py", line 123, in RunMain
    import gslib.__main__
  File "C:\Users\Itay\Desktop\HUDS\AFX\cef-project\tools\buildtools\external_bin\gsutil\gsutil_4.46\gsutil\gslib\__main__.py", line 75, in <module>
    from gslib.command_runner import CommandRunner
  File "C:\Users\Itay\Desktop\Hroject\tools\buildtools\external_bin\gsutil\gsutil_4.46\gsutil\gslib\command_runner.py", line 64, in <module>
    from gslib.tests.util import HAS_NON_DEFAULT_GS_HOST
  File "C:\Users\Itay\Desktop\HUDS\AFX\cef-project\tools\buildtools\external_bin\gsutil\gsutil_4.46\gsutil\gslib\tests\util.py", line 126, in <module>
    TEST_ENCRYPTION_KEY1_SHA256_B64 = Base64Sha256FromBase64EncryptionKey(
  File "C:\Users\Itay\Desktop\HUDS\AFX\cef-project\tools\buildtools\external_bin\gsutil\gsutil_4.46\gsutil\gslib\utils\encryption_helper.py", line 152, in Base64Sha256FromBase64EncryptionKey
    decoded_bytes = base64.decodestring(csek_encryption_key)
AttributeError: module 'base64' has no attribute 'decodestring'
]
UDS\AFX\cef-project\tools\buildtools\external_bin\gsutil\gsutil_4.46\gsutil\gslib\command_runner.py", line 64, in <module>
    from gslib.tests.util import HAS_NON_DEFAULT_GS_HOST
  File "C:\Users\Itay\Desktop\HUDS\AFX\cef-project\tools\buildtools\external_bin\gsutil\gsutil_4.46\gsutil\gslib\tests\util.py", line 126, in <module>
    TEST_ENCRYPTION_KEY1_SHA256_B64 = Base64Sha256FromBase64EncryptionKey(
  File "C:\Users\Itay\Desktop\HUDS\AFX\cef-project\tools\buildtools\external_bin\gsutil\gsutil_4.46\gsutil\gslib\utils\encryption_helper.py", line 152, in Base64Sha256FromBase64EncryptionKey
    decoded_bytes = base64.decodestring(csek_encryption_key)
AttributeError: module 'base64' has no attribute 'decodestring'
]
Downloading 1 files took 0.506643 second(s)
CMake Error at CMakeLists.txt:114 (message):
  Execution failed with unexpected result: 1

-- Configuring incomplete, errors occurred!
See also "C:/Users/Itay/Desktop/HUDS/AFX/cef-project/build/CMakeFiles/CMakeOutput.log".`

**### CMakeOutput.log:**

`The system is: Windows - 10.0.19042 - AMD64
Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
Compiler:  
Build flags: 
Id flags:  

The output was:
0
Microsoft (R) Build Engine version 16.8.2+25e4d540b for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 25/03/2021 22:09:51.
Project "C:\Users\Itay\Desktop\HUDS\AFX\cef-project\build\CMakeFiles\3.19.4\CompilerIdC\CompilerIdC.vcxproj" on node 1 (default targets).
PrepareForBuild:
  Creating directory "Debug\".
  Creating directory "Debug\CompilerIdC.tlog\".
InitializeBuildStatus:
  Creating "Debug\CompilerIdC.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
ClCompile:
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\HostX64\x64\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\" /Fd"Debug\vc142.pdb" /Gd /TC /FC /errorReport:queue CMakeCCompilerId.c
  CMakeCCompilerId.c
Link:
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\HostX64\x64\link.exe /ERRORREPORT:QUEUE /OUT:".\CompilerIdC.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\CompilerIdC.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\CompilerIdC.lib" /MACHINE:X64 Debug\CMakeCCompilerId.obj
  CompilerIdC.vcxproj -> C:\Users\Itay\Desktop\HUDS\AFX\cef-project\build\CMakeFiles\3.19.4\CompilerIdC\CompilerIdC.exe
PostBuildEvent:
  for %%i in (cl.exe) do @echo CMAKE_C_COMPILER=%%~$PATH:i
  :VCEnd
  CMAKE_C_COMPILER=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\Hostx64\x64\cl.exe
FinalizeBuildStatus:
  Deleting file "Debug\CompilerIdC.tlog\unsuccessfulbuild".
  Touching "Debug\CompilerIdC.tlog\CompilerIdC.lastbuildstate".
Done Building Project "C:\Users\Itay\Desktop\HUDS\AFX\cef-project\build\CMakeFiles\3.19.4\CompilerIdC\CompilerIdC.vcxproj" (default targets).

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:01.46

Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.exe"

Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.vcxproj"

The C compiler identification is MSVC, found in "C:/Users/Itay/Desktop/HUDS/AFX/cef-project/build/CMakeFiles/3.19.4/CompilerIdC/CompilerIdC.exe"

Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
Compiler:  
Build flags: 
Id flags:  

The output was:
0
Microsoft (R) Build Engine version 16.8.2+25e4d540b for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 25/03/2021 22:09:52.
Project "C:\Users\Itay\Desktop\HUDS\AFX\cef-project\build\CMakeFiles\3.19.4\CompilerIdCXX\CompilerIdCXX.vcxproj" on node 1 (default targets).
PrepareForBuild:
  Creating directory "Debug\".
  Creating directory "Debug\CompilerIdCXX.tlog\".
InitializeBuildStatus:
  Creating "Debug\CompilerIdCXX.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
ClCompile:
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\HostX64\x64\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\" /Fd"Debug\vc142.pdb" /Gd /TP /FC /errorReport:queue CMakeCXXCompilerId.cpp
  CMakeCXXCompilerId.cpp
Link:
  C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\HostX64\x64\link.exe /ERRORREPORT:QUEUE /OUT:".\CompilerIdCXX.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\CompilerIdCXX.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\CompilerIdCXX.lib" /MACHINE:X64 Debug\CMakeCXXCompilerId.obj
  CompilerIdCXX.vcxproj -> C:\Users\Itay\Desktop\HUDS\AFX\cef-project\build\CMakeFiles\3.19.4\CompilerIdCXX\CompilerIdCXX.exe
PostBuildEvent:
  for %%i in (cl.exe) do @echo CMAKE_CXX_COMPILER=%%~$PATH:i
  :VCEnd
  CMAKE_CXX_COMPILER=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\Hostx64\x64\cl.exe
FinalizeBuildStatus:
  Deleting file "Debug\CompilerIdCXX.tlog\unsuccessfulbuild".
  Touching "Debug\CompilerIdCXX.tlog\CompilerIdCXX.lastbuildstate".
Done Building Project "C:\Users\Itay\Desktop\HUDS\AFX\cef-project\build\CMakeFiles\3.19.4\CompilerIdCXX\CompilerIdCXX.vcxproj" (default targets).

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:00.84

Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.exe"

Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.vcxproj"

The CXX compiler identification is MSVC, found in "C:/Users/Itay/Desktop/HUDS/AFX/cef-project/build/CMakeFiles/3.19.4/CompilerIdCXX/CompilerIdCXX.exe"

Detecting C compiler ABI info compiled with the following output:
Change Dir: C:/Users/Itay/Desktop/HUDS/AFX/cef-project/build/CMakeFiles/CMakeTmp

Run Build Command(s):C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/MSBuild/Current/Bin/MSBuild.exe cmTC_928e3.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=16.0 /v:m && Microsoft (R) Build Engine version 16.8.2+25e4d540b for .NET Framework

Copyright (C) Microsoft Corporation. All rights reserved.

  Microsoft (R) C/C++ Optimizing Compiler Version 19.28.29334 for x64

  Copyright (C) Microsoft Corporation.  All rights reserved.

  CMakeCCompilerABI.c

  cl /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_928e3.dir\Debug\\" /Fd"cmTC_928e3.dir\Debug\vc142.pdb" /Gd /TC /errorReport:queue "C:\Program Files\CMake\share\cmake-3.19\Modules\CMakeCCompilerABI.c"

  cmTC_928e3.vcxproj -> C:\Users\Itay\Desktop\HUDS\AFX\cef-project\build\CMakeFiles\CMakeTmp\Debug\cmTC_928e3.exe

Detecting CXX compiler ABI info compiled with the following output:
Change Dir: C:/Users/Itay/Desktop/HUDS/AFX/cef-project/build/CMakeFiles/CMakeTmp

Run Build Command(s):C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/MSBuild/Current/Bin/MSBuild.exe cmTC_8e5b4.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=16.0 /v:m && Microsoft (R) Build Engine version 16.8.2+25e4d540b for .NET Framework

Copyright (C) Microsoft Corporation. All rights reserved.

  Microsoft (R) C/C++ Optimizing Compiler Version 19.28.29334 for x64

  Copyright (C) Microsoft Corporation.  All rights reserved.

  CMakeCXXCompilerABI.cpp

  cl /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_8e5b4.dir\Debug\\" /Fd"cmTC_8e5b4.dir\Debug\vc142.pdb" /Gd /TP /errorReport:queue "C:\Program Files\CMake\share\cmake-3.19\Modules\CMakeCXXCompilerABI.cpp"

  cmTC_8e5b4.vcxproj -> C:\Users\Itay\Desktop\HUDS\AFX\cef-project\build\CMakeFiles\CMakeTmp\Debug\cmTC_8e5b4.exe

`

**Comment by dtugend** [comment]
This project is still under development, so it's not fully ready yet, esepcially the afx_interop version 7.

The master branch is probably not fully functionial atm (sorry about that), the official HLAE is compatbile with the v3 branch (afx_interop version 6) released a while ago:  
https://github.com/advancedfx/afx-cefhud-interop/tree/v3

There's already pre-built binaries for this version here (linked in the About section of this repository as well):
https://drive.google.com/drive/folders/1CQFGMYhmz4x9DxunmwhWMp37ow6YOBON  
First install / extract the Release-Base.7z and over that replace with the contents from Release.7z - the AfxHookSource.7z is not needed, since the officcial HLAE fully supports the v6 by now.

If you want to build v3 / afx_interop_v6 yourself please:

- Obtain Visual Studio 2019 (e.g. Community edition) and make sure at least the "Desktop Development with C++ component" is installed.
- 
- Clone the v3 branch with git:
```
cd c/some/directory
git clone https://github.com/advancedfx/afx-cefhud-interop.git
git checkout origin v3
```

Now open the Start -> Visual Studios 2019 -> Developer Command Prompt for VS 2019

```
c:
cd c:\some\directory\afx-cefhud-interop
mkdir build
cd build
cmake -G "Visual Studio 16" -A x64 ..
```

Then, open the newly created build\cef.sln in Visual Studio 2019 and select Build > Build Solution.

**Comment by dtugend** [comment]
The above + make sure to do a release build, the older original 2019 CEF has multiple bugs and I am not sure if it works in Debug with the v3 branch.

**Comment by dtugend** [comment]
I am actually running in the same error now, let me see why it broke.

**Comment by dtugend** [comment]
Hi.
Thank you for your problem report.

It will be easiest if you clean out the current files your downloaded and start over with the short-instructions I made here:
https://github.com/advancedfx/afx-cefhud-interop/blob/main/README.md#short-instructions

The reason for it failing is that the download URLs for CEF changed and I hadn't merged the changed ones yet.

**Comment by dtugend** [comment]
For instructions how to use the binary see the comments at the top of the example.html here:
https://github.com/advancedfx/afx-cefhud-interop/blob/main/afx-cefhud-interop/example.html

**Comment by dtugend** [comment]
If you want a sneak peek at the first steps of the v7: https://github.com/advancedfx/afx-cefhud-interop/releases/tag/v7.0.0-da23af3
But keep in mind it's not production ready yet.
